const UPDATE_KEY = "UPDATE_KEY"
const UPDATE_CURRENT_CONDITION = "UPDATE_CURRENT_CONDITION";
const UPDATE_5_DAYS_FORECAST = "UPDATE_5_DAYS_FORECAST";


export { UPDATE_KEY, UPDATE_CURRENT_CONDITION, UPDATE_5_DAYS_FORECAST};
